// <auto-generated />
namespace FadlZ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class step11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(step11));
        
        string IMigrationMetadata.Id
        {
            get { return "202204212006001_step11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
